on: push

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ministryofjustice/github-actions/code-formatter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
